name: "Shogun"
honorMultiplier: 1
---
name: "Samurai"
honorMultiplier: 2
---
name: "Ninja"
honorMultiplier: 1
---
name: "Ninja"
honorMultiplier: 1
---
name: "Ninja"
honorMultiplier: 1
---
name: "Ronin"
honorMultiplier: 3

